---

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - jest
  - prettier

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - prettier
  - prettier/@typescript-eslint


env:
  jest: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  import/no-unresolved:
    - off

  arrow-body-style:
    - error
    - as-needed
    - requireReturnForObjectLiteral: false
  arrow-parens:
    - error
    - as-needed
  class-methods-use-this:
    - off
  curly:
    - error
    - multi-line
    - consistent
  implicit-arrow-linebreak:
    - off
  max-len:
    - error
    - 100
    - 2
  no-console:
    - error
    - allow:
      - info
      - error
  no-else-return:
    - error
    - allowElseIf: false
  no-multi-spaces:
    - error
    - ignoreEOLComments: true
  object-curly-newline:
    - error
    - ObjectExpression: { minProperties: 4, multiline: true, consistent: true }
      ObjectPattern: { multiline: true, consistent: true }
      ImportDeclaration: { multiline: true, consistent: true }
      ExportDeclaration: { minProperties: 4, multiline: true, consistent: true }
  radix:
    - off

# @typescript-eslint
  # Does not work with class fields :(
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  "@typescript-eslint/explicit-function-return-type":
    - off
  "@typescript-eslint/explicit-member-accessibility":
    - off
  "@typescript-eslint/indent":
    - off
  "@typescript-eslint/no-non-null-assertion":
    - off
  "@typescript-eslint/no-object-literal-type-assertion":
    - off

# eslint-plugin-jest
  jest/no-truthy-falsy:
    - error

# Custom rules
  prefer-early-return:
    - error
